"""add pricing_scenarios table

Revision ID: 81235de9ef5f
Revises: 456a8e2a0408
Create Date: 2026-08-05 14:43:17.140008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '81235de9ef5f'
down_revision = '456a8e2a0408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nb_cabinets_par_tier', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_scenarios')
    # ### end Alembic commands ###
